# Generated by Django 6.0.2 on 2026-03-05 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_poll_polloption_pollvote_post_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies_enabled', models.BooleanField(default=True)),
                ('trending_enabled', models.BooleanField(default=True)),
                ('milestones_enabled', models.BooleanField(default=True)),
                ('restricted_spikes_enabled', models.BooleanField(default=True)),
                ('badges_enabled', models.BooleanField(default=True)),
                ('momentum_enabled', models.BooleanField(default=True)),
                ('discussion_enabled', models.BooleanField(default=True)),
                ('daily_reflection_enabled', models.BooleanField(default=False)),
                ('max_notifications_per_hour', models.IntegerField(default=10)),
                ('max_notifications_per_day', models.IntegerField(default=50)),
                ('quiet_hours_start', models.IntegerField(default=23)),
                ('quiet_hours_end', models.IntegerField(default=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('REPLY', 'Someone replied to your thought'), ('TRENDING', 'Your post is trending'), ('MILESTONE', 'Engagement milestone reached'), ('RESTRICTED_SPIKE', 'Activity spike in Restricted Zone'), ('BADGE_EARNED', 'New badge earned'), ('MOMENTUM', 'Post gaining momentum'), ('DISCUSSION', 'Your thought sparked discussions')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_f2ad08_idx')],
            },
        ),
    ]
