version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=void_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:7-alpine

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/void_db
      - CELERY_BROKER_URL=redis://redis:6379/1
      - DEBUG=True
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: celery -A core worker -l info
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/void_db
      - CELERY_BROKER_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=https://void-backend-kia3.onrender.com/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
