# Generated by Django 6.0.2 on 2026-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_poll_polloption_pollvote_post_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='geo_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='geo_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='geo_privacy_radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_ephemeral',
            field=models.BooleanField(default=False),
        ),
    ]
