# Generated by Django 6.0.2 on 2026-03-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_post_expires_at_post_geo_latitude_post_geo_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_zk_verified',
            field=models.BooleanField(default=False),
        ),
    ]
