# Generated by Django 6.0.2 on 2026-03-05 04:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badge_type', models.CharField(choices=[('DEEP_THINKER', '🧠 Deep Thinker'), ('CHAOS_SPARK', '🔥 Chaos Spark'), ('MIDNIGHT_CONFESSOR', '🌙 Midnight Confessor'), ('DEBATE_MAGNET', '⚡ Debate Magnet'), ('ECHO_MAKER', '🔊 Echo Maker'), ('SHADOW_SAGE', '👁️ Shadow Sage'), ('PULSE_STARTER', '💫 Pulse Starter'), ('VOID_WALKER', '🌀 Void Walker')], max_length=25, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=10)),
                ('min_reputation_score', models.FloatField(default=0.0)),
                ('min_posts', models.IntegerField(default=0)),
                ('min_engagement_generated', models.IntegerField(default=0)),
                ('requires_restricted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_quality_score', models.FloatField(default=50.0)),
                ('report_avoidance_score', models.FloatField(default=100.0)),
                ('engagement_generated', models.FloatField(default=0.0)),
                ('positive_reaction_ratio', models.FloatField(default=0.5)),
                ('composite_score', models.FloatField(default=50.0)),
                ('total_posts', models.IntegerField(default=0)),
                ('total_reactions_received', models.IntegerField(default=0)),
                ('total_reports_against', models.IntegerField(default=0)),
                ('total_engagement', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-composite_score'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='reputation.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
