# Generated by Django 6.0.2 on 2026-03-05 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_poll_polloption_pollvote_post_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostRankingScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engagement_score', models.FloatField(default=0.0)),
                ('recency_score', models.FloatField(default=1.0)),
                ('comment_depth_score', models.FloatField(default=0.0)),
                ('dwell_time_score', models.FloatField(default=0.0)),
                ('reaction_diversity_score', models.FloatField(default=0.0)),
                ('report_penalty', models.FloatField(default=0.0)),
                ('composite_score', models.FloatField(db_index=True, default=0.0)),
                ('restricted_composite_score', models.FloatField(db_index=True, default=0.0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='content.post')),
            ],
            options={
                'ordering': ['-composite_score'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefers_restricted', models.FloatField(default=0.0)),
                ('prefers_long_content', models.FloatField(default=0.5)),
                ('prefers_polls', models.FloatField(default=0.5)),
                ('prefers_controversial', models.FloatField(default=0.5)),
                ('reaction_similarity_vector', models.JSONField(blank=True, default=dict)),
                ('avg_dwell_time_ms', models.IntegerField(default=0)),
                ('avg_session_duration_min', models.IntegerField(default=0)),
                ('preferred_time_of_day', models.IntegerField(default=12)),
                ('is_cold_start', models.BooleanField(default=True)),
                ('interactions_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feed_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
