# Generated by Django 6.0.2 on 2026-03-05 04:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_poll_polloption_pollvote_post_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementVelocity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reactions_1h', models.IntegerField(default=0)),
                ('reactions_6h', models.IntegerField(default=0)),
                ('reactions_24h', models.IntegerField(default=0)),
                ('comments_1h', models.IntegerField(default=0)),
                ('comments_6h', models.IntegerField(default=0)),
                ('comments_24h', models.IntegerField(default=0)),
                ('acceleration_score', models.FloatField(default=0.0)),
                ('reaction_type_count', models.IntegerField(default=0)),
                ('max_comment_depth', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='velocity', to='content.post')),
            ],
            options={
                'ordering': ['-acceleration_score'],
            },
        ),
        migrations.CreateModel(
            name='TrendingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('TRENDING_NOW', '🔥 Trending Now'), ('DARK_RISING', '🌑 Dark Rising'), ('MOST_DISCUSSED', '💬 Most Discussed'), ('RAPID_GROWTH', '⚡ Rapid Growth')], max_length=20)),
                ('velocity_score', models.FloatField(default=0.0)),
                ('rank_position', models.IntegerField(default=0)),
                ('snapshot_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trending_entries', to='content.post')),
            ],
            options={
                'ordering': ['rank_position'],
                'indexes': [models.Index(fields=['category', 'is_active', 'rank_position'], name='trending_tr_categor_358d2f_idx')],
            },
        ),
    ]
